#!/usr/bin/env bash
set -o pipefail

jenkins_crumb=$( curl -s 'https://jenkins-devops.secmet.co/crumbIssuer/api/json' | jq -r '.crumb')
curl -s -k -L -X POST -H "$jenkins_crumb" -F "jenkinsfile=<$1" \
	"https://jenkins-devops.secmet.co/pipeline-model-converter/validate"
