#!/usr/bin/env bash
set -o pipefail

jenkins_crumb=$(curl -s -k 'https://jenkins-devops.secmet.co/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)')
curl -k -X POST -H "$jenkins_crumb" -F "jenkinsfile=$1" \
	"https://jenkins-devops.secmet.co/pipeline-model-converter/validate"
