#!/usr/bin/env sh
set -eu

selected_issue="$(jira sprint list --current --plain --no-headers --columns "STATUS,ASSIGNEE,SUMMARY" -s~Done | fzf)"

jira issue view "$(echo $selected_issue | awk '{print $1}')"
