vim.api.nvim_create_user_command("GitPushWithReview", function()
      vim.cmd.Gwrite()
      local message = vim.fn.input("Commit message: ")
      vim.cmd.Git({ args = { "commit", "-m", message } })
      vim.cmd.Git({ args = { "pushg" } })
end, {})

vim.api.nvim_create_user_command("GitPush", function()
      vim.cmd.Gwrite()
      local message = vim.fn.input("Commit message: ")
      vim.cmd.Git({ args = { "commit", "-m", message } })
      vim.cmd.Git({ args = { "push" } })
end, {})
