#!/usr/bin/env bash
set -euo pipefail

vieb_bin=$(command -v vieb)
tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

kitty --class=float -e bash -c "fzf -m < ~/.vieb/quickmarks > $tmpfile"

mapfile -t urls < <(awk '{print $NF}' "$tmpfile")
[ "${#urls[@]}" -gt 0 ] && "$vieb_bin" --no-sandbox "${urls[@]}"
exit 0
