#! /bin/sh

sxhkd &

SCREEN_COUNT="$(xrandr | grep -c -w connected)"
pkill polybar

if [[ $SCREEN_COUNT > 1 ]]
then
  bspc monitor DP1-2-8 -d  5 6 7 8
  bspc monitor DP2-2 -d 1 2 3 4

  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example -c ~/.config/polybar/bspwm-config &
  done
else
  m=$(xrandr --query | grep " connected" | cut -d" " -f1); 
  bspc monitor $m -d 1 2 3 4 5 6 7 8  
  MONITOR=$m polybar --reload example -c ~/.config/polybar/bspwm-config &
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config remove_disabled_monitors true
#bspc config remove_unplugged_monitors true

# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# app startup
xfsettingsd &
# hsetroot -solid "#0B5C70" &
nitrogen --restore &
# compton -b --config ~/.config/compton.conf &
setxkbmap -option caps:escape &
nm-applet &
pamac-tray &

wmname LG3D & # This used to make intellij work with bspwm



