#! /bin/sh

# sxhkd &

SCREEN_COUNT="$(polybar -m | wc -l)"
pkill polybar

if [[ $SCREEN_COUNT = 2 ]]
then
  i=1
  a=1
  for m in $(polybar -m | cut -d " " -f1 | cut -d ":" -f1); do
    echo $m  $i $((i+1)) $((i+2)) $((i+3))
    bspc monitor ^$a -d $i $((i+1)) $((i+2)) $((i+3))
    MONITOR=$m polybar --reload example -c ~/.config/polybar/bspwm-config &
    ((i+=4))
    ((a+=1))
  done
else
  m=$(polybar -m | cut -d " " -f1 | cut -d ":" -f1); 
  bspc monitor $m -d 1 2 3 4 5 6 7 8  
  MONITOR=$m polybar --reload example -c ~/.config/polybar/bspwm-config &
fi

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# app startup
xfsettingsd &
# hsetroot -solid "#0B5C70" &
nitrogen --restore &
# compton -b --config ~/.config/compton.conf &
setxkbmap -option caps:escape &
nm-applet &
pamac-tray &

wmname LG3D & # This used to make intellij work with bspwm



