#!/usr/bin/env python3
from urllib import parse
import os
url = parse.urlparse(os.getenv('QUTE_URL'))
path = str(url.path) + str(url.fragment)
os.system(f"echo -n '{path}' | xclip -selection clip")
os.system(f"echo -n 'message-info \"copied {path} to clipboard\"' >> $QUTE_FIFO")
