return {
--   {
--     "ibhagwan/fzf-lua",
--     config = function()
--       local actions = require("fzf-lua").actions
--       require('fzf-lua').setup({
--         winopts = {
--           on_create = function()
--             local function feedkeys(normal_key, insert_key)
--               vim.keymap.set("n", normal_key, function()
--                 vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("i", true, false, true) or "", "n", true)
--                 vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(insert_key, true, false, true) or "", "n", true)
--                 vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-\\><C-n>", true, false, true) or "", "n", true)
--               end, { nowait = true, noremap = true, buffer = vim.api.nvim_get_current_buf() })
--             end
--             feedkeys("j", "<c-n>")
--             feedkeys("k", "<c-p>")
--             feedkeys("f", "<c-f>")
--             feedkeys("b", "<c-b>")
--             feedkeys("q", "<Esc>")
--           end,
--         },
--         keymap = {
--           -- Below are the default binds, setting any value in these tables will override
--           -- the defaults, to inherit from the defaults change [1] from `false` to `true`
--           builtin = {
--             -- neovim `:tmap` mappings for the fzf win
--             -- true,        -- uncomment to inherit all the below in your custom config
--             ["<M-Esc>"]    = "hide", -- hide fzf-lua, `:FzfLua resume` to continue
--             ["<F1>"]       = "toggle-help",
--             ["<F2>"]       = "toggle-fullscreen",
--             -- Only valid with the 'builtin' previewer
--             ["<F3>"]       = "toggle-preview-wrap",
--             ["<F4>"]       = "toggle-preview",
--             -- Rotate preview clockwise/counter-clockwise
--             ["<F5>"]       = "toggle-preview-ccw",
--             ["<F6>"]       = "toggle-preview-cw",
--             -- `ts-ctx` binds require `nvim-treesitter-context`
--             ["<F7>"]       = "toggle-preview-ts-ctx",
--             ["<F8>"]       = "preview-ts-ctx-dec",
--             ["<F9>"]       = "preview-ts-ctx-inc",
--             ["<S-Left>"]   = "preview-reset",
--             ["<S-down>"]   = "preview-page-down",
--             ["<S-up>"]     = "preview-page-up",
--             ["<M-S-down>"] = "preview-down",
--             ["<M-S-up>"]   = "preview-up",
--             ["ctrl-j"]     = "preview-up",
--             ["ctrl-k"]     = "preview-down",
--           },
--           fzf = {
--             -- fzf '--bind=' options
--             -- true,        -- uncomment to inherit all the below in your custom config
--             ["ctrl-z"]     = "abort",
--             -- ["ctrl-u"]     = "unix-line-discard",
--             ["ctrl-d"]     = "half-page-down",
--             ["ctrl-u"]     = "half-page-up",
--             ["ctrl-a"]     = "beginning-of-line",
--             ["ctrl-e"]     = "end-of-line",
--             ["alt-a"]      = "toggle-all",
--             ["alt-g"]      = "first",
--             ["alt-G"]      = "last",
--             -- Only valid with fzf previewers (bat/cat/git/etc)
--             ["f3"]         = "toggle-preview-wrap",
--             ["f4"]         = "toggle-preview",
--             ["shift-down"] = "preview-page-down",
--             ["shift-up"]   = "preview-page-up",
--           },
--         },
--         actions = {
--           -- Below are the default actions, setting any value in these tables will override
--           -- the defaults, to inherit from the defaults change [1] from `false` to `true`
--           files = {
--             -- true,        -- uncomment to inherit all the below in your custom config
--             -- Pickers inheriting these actions:
--             --   files, git_files, git_status, grep, lsp, oldfiles, quickfix, loclist,
--             --   tags, btags, args, buffers, tabs, lines, blines
--             -- `file_edit_or_qf` opens a single selection or sends multiple selection to quickfix
--             -- replace `enter` with `file_edit` to open all files/bufs whether single or multiple
--             -- replace `enter` with `file_switch_or_edit` to attempt a switch in current tab first
--             ["enter"]  = actions.file_edit_or_qf,
--             ["ctrl-x"] = actions.file_split,
--             ["ctrl-v"] = actions.file_vsplit,
--             ["ctrl-t"] = actions.file_tabedit,
--             ["alt-q"]  = actions.file_sel_to_qf,
--             ["alt-Q"]  = actions.file_sel_to_ll,
--             ["alt-i"]  = actions.toggle_ignore,
--             ["alt-h"]  = actions.toggle_hidden,
--             ["alt-f"]  = actions.toggle_follow,
--             ["ctrl-j"] = actions.ex
--           },
--         }
--       })
--     end
--   }
}
